VideoCourse/Entities/Course.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace VideoCourse.Entities
{
    public class Course
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(255)]
        public string ImageUrl { get; set; }
        [MaxLength(255)]
        public string MarqueeImageUrl { get; set; }
        [MaxLength(80), Required]
        public string Title { get; set; }
        [MaxLength(1024)]
        public string Description { get; set; }

        public int InstructorId { get; set; }
        public Instructor Instructor { get; set; }
        public List<Module> Modules { get; set; }
        public List<Video> Videos { get; set; }
        public List<UserCourse> UserCourses { get; set; }
    }
}

VideoCourse/Entities/Video.cs
using System.ComponentModel.DataAnnotations;

namespace VideoCourse.Entities
{
    public class Video
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(80), Required]
        public string Title { get; set; }
        [MaxLength(1024)]
        public string Description { get; set; }
        public int Duration { get; set; }
        [MaxLength(1024)]
        public string Thumbnail { get; set; }
        [MaxLength(1024)]
        public string Url { get; set; }
        public int Position { get; set; }

        public int ModuleId { get; set; }
        public int CourseId { get; set; } // Side-step from 3rd normal form for easier access to a video's course

        public virtual Module Module { get; set; }

        public virtual Course Course { get; set; }
    }
}

VideoCourse/Models/MembershipViewModels/CourseViewModel.cs
using System.Collections.Generic;
using VideoCourse.Models.DTOModels;

namespace VideoCourse.Models.MembershipViewModels
{
    public class CourseViewModel
    {
        public CourseDTO Course { get; set; }
        public InstructorDTO Instructor { get; set; }
        public IEnumerable<ModuleDTO> Modules { get; set; }
    }
}

VideoCourse/Models/MembershipViewModels/DashboardViewModel.cs
using System.Collections.Generic;
using VideoCourse.Models.DTOModels;

namespace VideoCourse.Models.MembershipViewModels
{
    public class DashboardViewModel
    {
        public List<List<CourseDTO>> Courses { get; set; }
    }
}

VideoCourse/Models/MembershipViewModels/VideoViewModel.cs
using VideoCourse.Models.DTOModels;

namespace VideoCourse.Models.MembershipViewModels
{
    public class VideoViewModel
    {
        public VideoDTO Video { get; set; }
        public InstructorDTO Instructor { get; set; }
        public CourseDTO Course { get; set; }
        public LessonInfoDTO LessonInfo { get; set; }
    }
}

VideoCourse/Controllers/MembershipController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using VideoCourse.Models;
using AutoMapper;
using VideoCourse.Repositories;
using VideoCourse.Models.DTOModels;
using VideoCourse.Models.MembershipViewModels;

namespace VideoCourse.Controllers
{
    public class MembershipController : Controller
    {
        private string _userId;
        private IReadRepository _db;
        private readonly IMapper _mapper;
        public MembershipController(IHttpContextAccessor httpContextAccessor, 
            UserManager<ApplicationUser> userManager, IMapper mapper, IReadRepository db)
        {
            // Get Logged in user's UserId
            var user = httpContextAccessor.HttpContext.User;
            _userId = userManager.GetUserId(user);
            _db = db;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Dashboard()
        {
            var courseDtoObjects = _mapper.Map<List<CourseDTO>>(_db.GetCourses(_userId));

            var dashboardModel = new DashboardViewModel();
            dashboardModel.Courses = new List<List<CourseDTO>>();
            var noOfRows = courseDtoObjects.Count <= 3 ? 1 : courseDtoObjects.Count / 3;
            for (var i = 0; i < noOfRows; i++)
            {
                dashboardModel.Courses.Add(courseDtoObjects.Take(3).ToList());
            }
            return View(dashboardModel);
        }

        [HttpGet]
        public IActionResult Course(int id)
        {
            var course = _db.GetCourse(_userId, id);
            var mappedCourseDTOs = _mapper.Map<CourseDTO>(course);
            var mappedInstructorDTO = _mapper.Map<InstructorDTO>(course.Instructor);
            var mappedModuleDTOs = _mapper.Map<List<ModuleDTO>>(course.Modules);

            for (var i = 0; i < mappedModuleDTOs.Count; i++)
            {
                mappedModuleDTOs[i].Downloads = course.Modules[i].Downloads.Count.Equals(0) ? null : _mapper.Map<List<DownloadDTO>>(course.Modules[i].Downloads);
                mappedModuleDTOs[i].Videos = course.Modules[i].Videos.Count.Equals(0) ? null : _mapper.Map<List<VideoDTO>>(course.Modules[i].Videos);
            }

            var courseModel = new CourseViewModel
            {
                Course = mappedCourseDTOs,
                Instructor = mappedInstructorDTO,
                Modules = mappedModuleDTOs
            };

            return View(courseModel);
        }

        [HttpGet]
        public IActionResult Video(int id)
        {
            var video = _db.GetVideo(_userId, id);
            var course = _db.GetCourse(_userId, video.CourseId);
            var mappedVideoDTO = _mapper.Map<VideoDTO>(video);
            var mappedCourseDTO = _mapper.Map<CourseDTO>(course);
            var mappedInstructorDTO = _mapper.Map<InstructorDTO>(course.Instructor);

            // Create a LessonInfoDto object
            var videos = _db.GetVideos(_userId, video.ModuleId).ToList();
            var count = videos.Count();
            var index = videos.IndexOf(video);
            var previous = videos.ElementAtOrDefault(index - 1);
            var previousId = previous == null ? 0 : previous.Id;
            var next = videos.ElementAtOrDefault(index + 1);
            var nextId = next == null ? 0 : next.Id;
            var nextTitle = next == null ? string.Empty : next.Title;
            var nextThumb = next == null ? string.Empty : next.Thumbnail;

            var videoModel = new VideoViewModel
            {
                Video = mappedVideoDTO,
                Instructor = mappedInstructorDTO,
                Course = mappedCourseDTO,
                LessonInfo = new LessonInfoDTO
                {
                    LessonNumber = index + 1,
                    NumberOfLessons = count,
                    NextVideoId = nextId,
                    PreviousVideoId = previousId,
                    NextVideoTitle = nextTitle,
                    NextVideoThumbnail = nextThumb,
                    CurrentVideoTitle = video.Title,
                    CurrentVideoThumbnail = video.Thumbnail
                }
            };

            return View(videoModel);
        }
    }
}

VideoCourse/Controllers/VideosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VideoCourse.Data;
using VideoCourse.Entities;
using Microsoft.AspNetCore.Authorization;

namespace VideoCourse.Controllers
{
    [Authorize(Roles = "Admin")]
    [Route("admin/[controller]/[action]")]
    public class VideosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VideosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Videos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Videos.ToListAsync());
        }

        // GET: Videos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var video = await _context.Videos
                .SingleOrDefaultAsync(m => m.Id == id);
            if (video == null)
            {
                return NotFound();
            }

            return View(video);
        }

        // GET: Videos/Create
        public IActionResult Create()
        {
            ViewData["ModuleId"] = new SelectList(_context.Modules, "Id", "Title");
            return View();
        }

        // POST: Videos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Duration,Thumbnail,Url,Position,ModuleId,CourseId")] Video video)
        {
            if (ModelState.IsValid)
            {
                _context.Add(video);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["ModuleId"] = new SelectList(_context.Modules, "Id", "Title");
            return View(video);
        }

        // GET: Videos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var video = await _context.Videos.SingleOrDefaultAsync(m => m.Id == id);
            if (video == null)
            {
                return NotFound();
            }
            ViewData["ModuleId"] = new SelectList(_context.Modules, "Id", "Title");
            return View(video);
        }

        // POST: Videos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Duration,Thumbnail,Url,Position,ModuleId,CourseId")] Video video)
        {
            if (id != video.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(video);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VideoExists(video.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }

            ViewData["ModuleId"] = new SelectList(_context.Modules, "Id", "Title");
            return View(video);
        }

        // GET: Videos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var video = await _context.Videos
                .SingleOrDefaultAsync(m => m.Id == id);
            if (video == null)
            {
                return NotFound();
            }

            return View(video);
        }

        // POST: Videos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var video = await _context.Videos.SingleOrDefaultAsync(m => m.Id == id);
            _context.Videos.Remove(video);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool VideoExists(int id)
        {
            return _context.Videos.Any(e => e.Id == id);
        }
    }
}

VideoCourse/Views/Membership/Course.cshtml
@model CourseViewModel

@{
    ViewData["Title"] = "Course";
}

<div class="membership top-margin course-content">
    <div class="row navigation-bar">
        <div class="col-sm-12">
            <a class="btn btn-primary" href="~/Membership/Dashboard">
                <span class="glyphicon glyphicon-menu-left"></span>Back to Dashboard
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="panel">
                <div class="marquee" style="background-image: url('@Model.Course.MarqueeImageUrl');">
                    <img src="@Model.Course.CourseImageUrl" class="cover-image">
                </div>
                <div class="panel-body">
                    <h1>@Model.Course.CourseTitle</h1>
                    <h4 class="product-desc">@Model.Course.CourseDescription</h4>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-9">
            @foreach (var module in Model.Modules)
            {
                <div class="panel module">
                    <div class="panel-body">
                        <h5>@module.ModuleTitle</h5>
                    </div>
                    @if (module.Videos != null)
                    {
                        @await Html.PartialAsync("_ModuleVideosPartial", module.Videos)
                    }
                    @if (module.Downloads != null)
                    {
                        <hr class="no-margin">
                        <div class="panel-body download-panel">
                            <h5>Downloads</h5>
                            @await Html.PartialAsync("_ModuleDownloadsPartial", module.Downloads)
                        </div>
                    }
                </div>
            }
        </div>
        <div class="col-sm-3">
            @if (Model.Instructor != null)
            {
                @await Html.PartialAsync("_InstructorBioPartial", Model.Instructor)
            }
        </div>
    </div>
</div>

VideoCourse/Views/Membership/Dashboard.cshtml
@model DashboardViewModel

@{
    ViewData["Title"] = "Dashboard";
}

<div class="membership top-margin">
    <h2 class="text-dark">Dashboard</h2>
    <hr class="thick margin">
    @foreach (var dashboardRow in Model.Courses)
    {
        <div class="row">
            @foreach (var course in dashboardRow)
            {
                @await Html.PartialAsync("_CoursePanelPartial", course)
            }
        </div>
    }
</div>

VideoCourse/Views/Membership/Video.cshtml
@model VideoViewModel

@{
    ViewData["Title"] = "Video";
}

<div class="membership top-margin video-content">
    <div class="row navigation-bar">
        <div class="col-sm-12">
            <a class="btn btn-primary" href="~/Membership/Course/@Model.Course.CourseId">
                <span class="glyphicon glyphicon-menu-left"></span>Back to @Model.Course.CourseTitle
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-9">
            @if (Model != null && Model.Video != null && Model.LessonInfo != null && Model.Course != null)
            {
                @await Html.PartialAsync("_VideoPlayerPartial", Model)
            }
        </div>

        <div class="col-sm-3">
            @if (Model != null && Model.LessonInfo != null)
            {
                @await Html.PartialAsync("_VideoComingUpPartial", Model.LessonInfo)
            }
            @if (Model != null && Model.Instructor != null)
            {
                @await Html.PartialAsync("_InstructorBioPartial", Model.Instructor)
            }
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        $(function () {
            jwplayer("video").setup({
                file: $("#hiddenUrl").text(),
                image: $("#hiddenImageUrl").text()
            });
        });
    </script>
}

VideoCourse/Views/Membership/_CoursePanelPartial.cshtml
@model CourseDTO

<div class="col-sm-4">
    <div class="panel course-listing">
        <img class="thumb" src="@Model.CourseImageUrl">
        <div class="panel-body">
            <h3 class="text-dark">@Model.CourseTitle</h3>
            <p>@Model.CourseDescription</p>
            <a class="btn btn-primary" href="~/Membership/Course/@Model.CourseId">View Course</a>
        </div>
    </div>
</div>

@*@using (Html.BeginForm("Course", "Membership", FormMethod.Post))
{
    @Html.HiddenFor(model => model.CourseId, new { id = "HiddenCourseId" })

    <input type = "submit" value = "Enter the value" />

}*@ 

VideoCourse/Views/Membership/_InstructorBioPartial.cshtml
@model InstructorDTO

<div class="instructor-bio panel">
    <div class="panel-body">
        <img src="@Model.InstructorAvatar" class="avatar img-circle">
        <h4>@Model.InstructorName</h4>
        <h5 class="text-primary">Instructor</h5>
        <p>@Model.InstructorDescription</p>
    </div>
</div>

VideoCourse/Views/Membership/_ModuleDownloadsPartial.cshtml
@model IEnumerable<DownloadDTO>

<ul>
    @foreach (var download in Model)
    {
        <li>
            <a href="@download.DownloadUrl" target="_blank">
                <span class="glyphicon glyphicon-download-alt"></span>&nbsp;@download.DownloadTitle
            </a>
        </li>
    }
</ul>

VideoCourse/Views/Membership/_ModuleVideosPartial.cshtml
@model IEnumerable<VideoDTO>

@foreach (var video in Model)
{
    <div class="panel-body module-video">
        <a href="~/Membership/Video/@video.Id">
            <div class="media">
                <div class="media-left hidden-xs">
                    <div class="thumb-container">
                        <img src="@video.Thumbnail" class="thumb">
                    </div>
                </div>
                <div class="media-body">
                    <h5>@video.Title</h5>
                    <p class="text-light">
                        <i class="glyphicon glyphicon-time"></i>
                        @video.Duration minutes
                    </p>
                    <p>@video.Description</p>
                </div>
                <div class="media-right hidden-xs text-light">
                    <i class="glyphicon glyphicon-chevron-right"></i>
                </div>
            </div>
        </a>
    </div>
}

VideoCourse/Views/Membership/_VideoComingUpPartial.cshtml
@model LessonInfoDTO

@if (Model.PreviousVideoId > 0 || Model.NextVideoId > 0)
{
    <div class="panel coming-up">
        @if (Model.NextVideoId == 0)
        {
            <img src="@Model.CurrentVideoThumbnail" class="img-responsive">
        }
        else
        {
            <img src="@Model.NextVideoThumbnail" class="img-responsive">
        }
        
        <div class="panel-body">
            @if (Model.NextVideoId == 0)
            {
                <p>COURSE COMPLETED</p>
                <h5>@Model.CurrentVideoTitle</h5>

            }
            else
            {
                <p>COMING UP</p>
                <h5>@Model.NextVideoTitle</h5>
            }
            
            <div class="btn-group" role="group">
                @if (Model.PreviousVideoId == 0)
                {
                    <a class="btn btn-default" disabled href="#">Previous</a>
                }
                else
                {
                    <a class="btn btn-default" href="~/Membership/Video/@Model.PreviousVideoId">Previous</a>
                }
                @if (Model.NextVideoId == 0)
                {
                    <a class="btn btn-default" disabled href="#">Next</a>
                }
                else
                {
                    <a class="btn btn-default" href="~/Membership/Video/@Model.NextVideoId">Next</a>
                }
            </div>
        </div>
    </div>
}

VideoCourse/Views/Membership/_VideoPlayerPartial.cshtml
@model VideoViewModel

<div class="panel">
    @if (Model.Video.Url != null)
    {
        <div id="video" class="video-margin">&nbsp;</div>
        <div id="hiddenUrl" hidden="hidden">@Model.Video.Url</div>
        <div id="hiddenImageUrl" hidden="hidden">@Model.Video.Thumbnail</div>
    }

    <div class="panel-body">
        <h2 class="text-dark">@Model.Video.Title</h2>
        <p class="text-light">
            <i class="glyphicon glyphicon-facetime-video"></i>
            Lesson @Model.LessonInfo.LessonNumber/@Model.LessonInfo.NumberOfLessons&nbsp;&nbsp;
            <i class="glyphicon glyphicon-time"></i>
            @Model.Video.Duration minutes
        </p>
        <div class="media-object">
            <div class="media-left">
                <img src="@Model.Course.CourseImageUrl">
            </div>
            <div class="media-body media-middle">
                <p>@Model.Course.CourseTitle</p>
            </div>
        </div>
    </div>

    <hr class="no-margin">
    <div class="panel-body">
        @Model.Video.Description
    </div>
</div>